version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: nodejs_course
    container_name: nodejs_course_web
    env_file:
      - ./.env
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
      - ${SECOND_EXTERNAL_PORT}:${SECOND_INTERNAL_PORT}
    volumes:
      - ./:/app
    networks:
      - default

  mysql:
    image: "mysql:5.7"
    container_name: nodejs_course_mysql
    ports:
      - "49165:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: nodejs_course
    volumes:
      - "./data/db:/var/lib/mysql"
    networks:
      - default

  mongodb:
    image: mongo
    container_name: nodejs_course_mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - 27017:27017
    networks:
      - default

networks:
  default:
    driver: bridge
