version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: nodejs_course
    container_name: nodejs_course
    env_file:
      - ./.env
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
      - ${SECOND_EXTERNAL_PORT}:${SECOND_INTERNAL_PORT}
    volumes:
      - ./:/app
